---
- name: Deploy Forgejo
  hosts: localhost
  become: true
  tasks:
    - name: Install Forgejo via EasyForgejo script
      shell: curl -sSL https://wkoszek.github.io/easyforgejo/install.sh | bash | tail -23 > FORGEJO.md
      args:
        creates: /usr/local/bin/forgejo

    - name: Apply security baseline to Forgejo config
      community.general.ini_file:
        path: /etc/forgejo/app.ini
        section: service
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - { option: 'DISABLE_REGISTRATION', value: 'true' }
        - { option: 'REQUIRE_SIGNIN_VIEW', value: 'true' }
        - { option: 'ENABLE_OPENID_SIGNUP', value: 'false' }
      notify: Restart Forgejo Service        

    - name: Configure Forgejo server block for localhost only
      community.general.ini_file:
        path: /etc/forgejo/app.ini  # Update this to your actual app.ini path
        section: server
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: 'HTTP_ADDR', value: '127.0.0.1' }
        - { key: 'DOMAIN', value: 'localhost' }
        - { key: 'LOCAL_ROOT_URL', value: 'http://localhost:3000/' }
      notify: Restart Forgejo Service        

    - name: Get status of the file
      ansible.builtin.stat:
        path: FORGEJO.md
      register: file_info

    - name: Debug if file exists
      ansible.builtin.debug:
        msg: "Read {{ playbook_dir }}/FORGEJO.md for further instructions."
      when: file_info.stat.exists
  handlers:
    - name: Restart Forgejo Service
      ansible.builtin.systemd:
        name: forgejo
        state: restarted
